# -------------------------------------------------
# File Name: 63_financial_executive_report.py
# Author: Florentino Baez
# Date: 12/03/2026
# Description: Generate executive summary text from finance pipeline outputs.
# -------------------------------------------------

from datetime import datetime
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR.parent / "data"
EXPORT_DIR = DATA_DIR / "exports"

CLEAN_INPUT = DATA_DIR / "financial_transactions_clean.csv"
CATEGORY_SUMMARY_INPUT = EXPORT_DIR / "financial_summary_by_category.csv"
MOM_INPUT = EXPORT_DIR / "financial_mom_growth.csv"
ANOMALY_INPUT = EXPORT_DIR / "financial_anomalies_flagged.csv"
SUMMARY_OUTPUT = EXPORT_DIR / "executive_summary.txt"


def safe_read_csv(path: Path) -> pd.DataFrame:
    if path.exists():
        return pd.read_csv(path)
    return pd.DataFrame()


def main() -> None:
    if not CLEAN_INPUT.exists():
        raise FileNotFoundError(
            f"Clean input not found: {CLEAN_INPUT}. Run 59_financial_cleaning_pipeline.py first."
        )

    EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(CLEAN_INPUT)
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
    df = df.dropna(subset=["date", "amount"]).copy()

    category_summary = safe_read_csv(CATEGORY_SUMMARY_INPUT)
    mom_growth = safe_read_csv(MOM_INPUT)
    anomalies = safe_read_csv(ANOMALY_INPUT)

    report_date = datetime.now().strftime("%Y-%m-%d")
    period_start = df["date"].min().date()
    period_end = df["date"].max().date()
    total_tx = len(df)
    amount_series = pd.Series(df["amount"])
    total_spending = float(amount_series.sum())
    avg_tx = float(amount_series.mean())

    if not category_summary.empty and "total_amount" in category_summary.columns:
        top_row = category_summary.sort_values("total_amount", ascending=False).iloc[0]
        top_category = str(top_row["category"])
        top_pct = (float(top_row["total_amount"]) / total_spending) * 100 if total_spending else 0.0
    else:
        fallback_df = pd.DataFrame(
            df.groupby("category", as_index=False).agg(amount=("amount", "sum"))
        )
        fallback_rows = sorted(
            fallback_df.itertuples(index=False),
            key=lambda row: float(row[1]),
            reverse=True,
        )
        fallback_df = pd.DataFrame(fallback_rows, columns=["category", "amount"])
        fallback = fallback_df.iloc[0]
        top_category = str(fallback["category"])
        top_pct = (float(fallback["amount"]) / total_spending) * 100 if total_spending else 0.0

    p95 = df["amount"].quantile(0.95)
    anomaly_count = len(anomalies) if not anomalies.empty else int((df["amount"] > p95).sum())

    mom_latest_label = "N/A"
    mom_latest_value = "N/A"
    if not mom_growth.empty and {"month", "mom_growth_pct"}.issubset(mom_growth.columns):
        mom_growth = mom_growth.dropna(subset=["mom_growth_pct"]).copy()
        if not mom_growth.empty:
            latest = mom_growth.iloc[-1]
            mom_latest_label = str(latest["month"])
            mom_latest_value = f"{float(latest['mom_growth_pct']):+.2f}%"

    lines = [
        "EXECUTIVE SUMMARY",
        "-----------------------------------------",
        f"Report Date       : {report_date}",
        f"Period Covered    : {period_start} -> {period_end}",
        f"Total Transactions: {total_tx:,}",
        f"Total Spending    : ${total_spending:,.2f}",
        f"Avg Transaction   : ${avg_tx:,.2f}",
        f"Top Category      : {top_category} ({top_pct:.2f}%)",
        f"Anomalies Flagged : {anomaly_count:,} transactions (P95 threshold: ${p95:,.2f})",
        f"MoM Growth ({mom_latest_label}) : {mom_latest_value}",
        "-----------------------------------------",
        "",
        "Generated by:",
        f"- {Path(__file__).name}",
        "",
        "Data sources:",
        f"- {CLEAN_INPUT}",
        f"- {CATEGORY_SUMMARY_INPUT}",
        f"- {MOM_INPUT}",
        f"- {ANOMALY_INPUT}",
    ]

    SUMMARY_OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    print("=" * 68)
    print("             FINANCIAL EXECUTIVE REPORT COMPLETED")
    print("=" * 68)
    print(f"Summary file                 : {SUMMARY_OUTPUT}")
    print("\nPreview:")
    print("\n".join(lines[:11]))


if __name__ == "__main__":
    main()
